//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assign1_v6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iHotel_Model1Container : DbContext
    {
        public iHotel_Model1Container()
            : base("name=iHotel_Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> BookingSet { get; set; }
        public virtual DbSet<RoomInfor> RoomInforSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
    }
}
